# Generated by Django 4.2.1 on 2023-06-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noterecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todolist', models.CharField(max_length=256)),
                ('time', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
